############################################################
# Based on hall/guacamole
############################################################
From guacamole
ENTRYPOINT /bin/bash
#ENTRYPOINT ["monit","-v","-d","10","-Ic","/etc/monitrc"]
